# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~>3.0.13"
gem "middleman-livereload", "~> 3.1.0"
gem "manhattan", github: "kohactive/manhattan", branch: "0-4-0"
gem "primordial", github: "johnkoht/primordial"
gem 'bootstrap_sass_rails'
gem 'font_awesome_rails_sass', '0.1.0'

gem 'sqlite3', '~> 1.3.9'